### ISSUE TITLE
Provide no-instrumentation thread-based coroutines

### ISSUE THREAD

**Issue by stepancheg** [offbynull/coroutines#53]
Coroutines library could provide something like `ThreadCoroutinesRunner` that should be identical to `CoroutineRunner` except it allocates a thread for each coroutine, and executes a `Coroutine` in that thread. `Continuation.suspend()` would just pause that thread until resume is called.

Such coroutines would be obviously very expensive, however, such coroutine runner can be used without instrumentation. So `ThreadCoroutineRunner` runner could be used from IDE for basic unit-tests without any IDE setup, and production process will run instrumented coroutine.

**Comment by offbynull** [comment]
This may be unnecessary. Which IDE are you using? If it has Maven integration + you've set up your project as a Maven project, you can use the test-instrument goal.

> Such coroutines would be obviously very expensive

It depends. This library (along with others like it) is designed to satisfy a narrow set of usecases. Most of the time, the normal Java threading API is what you want.

**Comment by stepancheg** [comment]
I'm using Idea with proprietary build system.

**Comment by offbynull** [comment]
Would a custom class loader work? https://gist.github.com/offbynull/fcdbadbfe07360d507b1

You can make it so that your coroutine classes are loaded through that classloader. The classloader would instrument them before giving you the class.

**Comment by stepancheg** [comment]
That classloader requires URL to jar to be specified in constructor. I'm not sure how to get that URL if I'm starting a test from IDE (I mean in generic way, so when new developer sets up a project, they can just right-click on a test and execute it without specifying paths anywhere).

**Comment by offbynull** [comment]
I spent some time thinking about this. I don't think providing a second CoroutineRunner is a good idea.

- The first problem is that if there's a bug in the instrumentation logic, it won't get caught until you're running in production.
-  The second problem is that having two implementations causes confusion for the user.
-  The third problem is that some of the expected functionality wouldn't work with the second implementation. For example, you wouldn't be able to serialize/deserialize the stack.

I also investigated writing an IntelliJ plugin, but I decided against it as well. If I write a plugin for one IDE, I have to write plugins for all IDEs. It would end up being a maintenance nightmare.

Having said all that, if you can't change your build system to Maven, I would suggest trying the following: http://stackoverflow.com/questions/15203498/intellij-idea-11-running-a-shell-script-as-a-run-debug-configuration.

I'm closing this ticket end of day.

**Comment by stepancheg** [comment]
> The first problem is that if there's a bug in the instrumentation logic, it won't get caught until you're running in production.

There's also testing, developer servers, large integration tests etc.

> The second problem is that having two implementations causes confusion for the user.

More that coroutines themself? I doubt so.

> The third problem is that some of the expected functionality wouldn't work with the second implementation. For example, you wouldn't be able to serialize/deserialize the stack.

First, I don't think it is a big deal.

Second, it can be explicitly expressed in code. library could have something like `ThreadCompatibleCoutine` which is not serializable even when it is executed instrumented.

Anyway, it's your project, you know it better.

> Having said all that, if you can't change your build system to Maven, I would suggest trying the following

That won't work for me. We have many developers in our teams, and each project must be usable out of the box without manual configuration. Idea plugin won't work for the same reason (project must be usable without any plugin).

Shell script will likely also slow down startup, and will cause lots of problems in corner cases, like compatibility with debuggers, profilers, code coverage tools and so on.

**Comment by offbynull** [comment]
Well the only other thing I can suggest is forking the project and adding the classes you need. I promise there won't be any major changes between now and the release to support Java 9. Even with the changes to support Java 9, you'll likely be able to merge without any conflicts (Java 9 changes should only effect the instrumenter).

Sorry. I really wish I could be of more help. I have a full-time job that needs my attention + several other opensource projects in development -- my immediate concern with this project is to avoid complexity such that I can continue to support/maintain it with minimal effort.

If you do choose to fork it, you can ping me directly if you have any questions: offbynull__AT__gmail__DOT__com. I'll do my best to provide answers quickly.
