### ISSUE TITLE
The gradle plugin is compiled by jdk 1.9 can't apply to the project which jdk version is 1.8   

### ISSUE THREAD

**Issue by dunmengjun** [offbynull/coroutines#83]
the gradle error is 
`com/offbynull/coroutines/gradleplugin/CoroutinesPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

found in intellij idea

**Comment by offbynull** [comment]
This is expected. You can still instrument java8 bytecode, but you need to
use jdk9 or jdk10 to do it.

jdk8 is no longer supported.
