### ISSUE TITLE
Switch bug

### ISSUE THREAD

**Issue by aoqilinjian** [offbynull/coroutines#87]
java.lang.IllegalStateException: java.lang.IllegalStateException: Label offset position has not been resolved yet
	at com.offbynull.coroutines.instrumenter.MethodHasher$DumpToDaosMethodVisitor.visitTableSwitchInsn(MethodHasher.java:149)
	at org.objectweb.asm.tree.TableSwitchInsnNode.accept(TableSwitchInsnNode.java:105)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)

**Comment by aoqilinjian** [comment]
jdk 8  on 1.4.2

**Comment by blackhzj** [comment]
I faced the same problem. You can use the TestCase like that.
`
import com.offbynull.coroutines.user.Continuation;
import com.offbynull.coroutines.user.Coroutine;

// I mondify it based on ComplexTest in instrumenter/resources
public class SwitchTest implements Coroutine
{
	private static final Object LOCK1 = new Object();
	private static final Object LOCK2 = new Object();
	private StringBuilder builder;

	public String switchFun(Continuation c)
	{
		int arg1 = 2;
		int arg2 = 2;
		switch(arg1)
		{
			case 0:
				throw new RuntimeException("0");
			case 1:
				throw new RuntimeException("1");
			case 2:
				switch(arg2)
				{
					case 0:
						throw new RuntimeException("0");
					case 1:
						throw new RuntimeException("1");
					case 2:
					{
						runFun(c);
						return "OK!";
					}
					default:
						throw new RuntimeException("innerdefault");
				}
			default:
				throw new RuntimeException("default");
		}

	}

	@Override
	public void run(Continuation c) throws Exception
	{
		switchFun(c);
	}

	public void runFun(Continuation c)
	{
		builder.append("started\n");
		int i = 0;
		while(true)
		{
			int res = calcProxy(c, this, i);
			if(res != (5 + i + (i * i)))
			{
				throw new RuntimeException("test failed!");
			}
			i++;
			if(i == 10)
			{
				break;
			}
		}
	}

	private static int calcProxy(Continuation c, SwitchTest ct, int x)
	{
		try
		{
			return ct.calc(c, x);
		}
		catch(Exception e)
		{
			ct.builder.append(x).append('\n');
			synchronized(LOCK1)
			{
				c.suspend();
				synchronized(LOCK2)
				{
					return 5 + (x * x) + x;
				}
			}
		}
	}

	private int calc(Continuation c, int x)
	{
		synchronized(LOCK1)
		{
			return 5 + pow2(c, x) + x;
		}
	}

	private int pow2(Continuation c, int x)
	{
		synchronized(LOCK1)
		{
			synchronized(LOCK2)
			{
				if(x == 9)
				{
					throw new RuntimeException();
				}
				builder.append(x).append('\n');
				c.suspend();
				return x * x;
			}
		}
	}
}

`

**Comment by offbynull** [comment]
I'm out of country at the moment. I'll take a look at this once I'm back
home next week.

**Comment by aoqilinjian** [comment]
I test with your method，it‘s ok， thank you very match.

**Comment by offbynull** [comment]
A new release has been cut (1.5.3) and should be available on Maven central shortly.

Thank you @blackhzj and @aoqilinjian for your contribution.
